/*
 * edited by ChengZhi Zhao
 */
package myHangman;

import java.util.Arrays;
/**
 *
 * @author Arsh
 */
public class Highscores extends javax.swing.JFrame {

    /**
     * 
     * @param home
     */
    public Highscores(Home home) {
        initComponents();
        setBounds(300,300,600,434);
        setLocationRelativeTo(null);
        this.home = home;
    }

     /**
     * this method is use for display the score after the Play panel pass the score to here.
     * @param number pass by the Play Panel 
     */
    public void setScore(int number){
        int min = score[0];
        int t = 0;
        if(counter == MAX_CAPASITY){
            for (int i = 0; i < score.length; i++) {
                if(score[i] < min){
                    min = score[i];
                    t++;
                }
                score[t] = number;
            }
        }
        else{
            score[counter] = number;
            counter++;
        }
        Arrays.sort(score);
        first.setText("ABC...." + score[3]);
        second.setText("ABC...." + score[2]);
        third.setText("ABC...." + score[1]);
        fourth.setText("ABC...." + score[0]);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        highscoresTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        fourth = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        third = new javax.swing.JLabel();
        second = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        highscoresTitle.setFont(new java.awt.Font("Bauhaus 93", 2, 58)); // NOI18N
        highscoresTitle.setForeground(new java.awt.Color(51, 102, 255));
        highscoresTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscoresTitle.setText("HIGHSCORES");
        highscoresTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(highscoresTitle);
        highscoresTitle.setBounds(0, 40, 600, 80);

        backButton.setBackground(new java.awt.Color(51, 102, 255));
        backButton.setFont(new java.awt.Font("Bauhaus 93", 2, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 370, 50, 19);

        fourth.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        fourth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourth.setText("ABC.....0000");
        getContentPane().add(fourth);
        fourth.setBounds(170, 250, 260, 40);

        first.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        first.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        first.setText("ABC.....0000");
        getContentPane().add(first);
        first.setBounds(170, 130, 260, 40);

        third.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        third.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        third.setText("ABC.....0000");
        getContentPane().add(third);
        third.setBounds(170, 210, 260, 40);

        second.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        second.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        second.setText("ABC.....0000");
        getContentPane().add(second);
        second.setBounds(170, 170, 260, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    //added some variable
    private final int MAX_CAPASITY = 4;
    private int[] score = new int[MAX_CAPASITY];
    private static int counter = 0;
    private Home home;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel first;
    private javax.swing.JLabel fourth;
    private javax.swing.JLabel highscoresTitle;
    private javax.swing.JLabel second;
    private javax.swing.JLabel third;
    // End of variables declaration//GEN-END:variables
}
